---
spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-local-secrets.properties
server:
  port: 8443
  ssl:
    key-store: classpath:trust/springboot.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    key-password: ${KEY_PASSWORD}
